#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=1gb
#PBS -l walltime=24:00:00
#PBS -t 1-64
#PBS -q short 
#PBS -j oe
#PBS -o ./log/$PBS_ARRAYID.log

cd $PBS_O_WORKDIR

mkdir -p ./log

pc=50
samples=../0-genotypes/sampleids.txt
vcf=../0-genotypes/ALL.chrs.eur.biallelic.maf.vcf.gz
cov=../0-genotypes/covariates_genos.txt
bed=../0-phenotypes/phenotypes_$pc.bed.gz
thr=../1-permutations/results/permutations_$pc.thresholds.txt
out=./conditional_$pc

QTLtools cis --vcf $vcf --bed $bed --cov $cov --mapping $thr\
    --include-samples $samples --normal --chunk $PBS_ARRAYID 64\
    --out ${out}_$PBS_ARRAYID.txt
