#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=1gb
#PBS -l walltime=24:00:00
#PBS -t 1-64
#PBS -q short 
#PBS -j oe
#PBS -o /scratch/bio5789/log/$PBS_JOBID.log

cd $PBS_O_WORKDIR

pc=20
samples=../0-genotypes/sampleids.txt
vcf=/scratch/bio5789/genotypes/ALL.chrs.yri.biallelic.maf.vcf.gz
cov=../0-genotypes/covariates_genos.txt
bed=../0-phenotypes/phenotypes_$pc.bed.gz
thr=/scratch/bio5789/permutations/permutations_$pc.thresholds.txt
out=/scratch/bio5789/conditionalpass/conditional_$pc

QTLtools cis --vcf $vcf --bed $bed --cov $cov --mapping $thr\
    --include-samples $samples --normal --chunk $PBS_ARRAYID 64\
    --out ${out}_$PBS_ARRAYID.txt
